#!/usr/bin/bash
filename="serversinfo.txt"
while read eachline
do
	echo "$eachline"
done < $filename

====================================

#!/usr/bin/bash
cat serversinfo.txt | while read line
do
	echo "$line"
	echo "-----"
done
